# Generated by Django 2.2.5 on 2019-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortened_id', models.URLField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
